# Generated by Django 4.1.3 on 2022-11-29 20:03

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'Restaurant.json'


def load_data(apps, schema_editor):
    Restaurant = apps.get_model('client', 'Restaurant')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            try:
                name = obj['fields']['name']
                description = obj['fields']['description']
                location_lon = obj['fields'].get('location_lon', 0)
                location_lat = obj['fields'].get('location_lat', 0)
                operating_hours_start = obj['fields']['operating_hours_start']
                operating_hours_end = obj['fields']['operating_hours_end']
                owner_id = obj['fields']['owner_id']
                image_url = obj['fields']['image_url']
                location = fromstr(
                    f'POINT({location_lon} {location_lat})', srid=4326)
                Restaurant(name=name, description=description, location_lon=location_lon, location_lat=location_lat, operating_hours_start=operating_hours_start,
                           operating_hours_end=operating_hours_end, owner_id=owner_id, image_url=image_url, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
