# Generated by Django 4.1.3 on 2022-11-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_address',
        ),
    ]
