# Generated by Django 4.1.3 on 2022-12-04 10:53

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

R_DATA_FILENAME = 'Restaurant.json'
RO_DATA_FILENAME = 'RestaurantOwner.json'
O_DATA_FILENAME = 'Order.json'


def load_data(apps, schema_editor):
    RestaurantOwner = apps.get_model('client', 'RestaurantOwner')
    ro_jsonfile = Path(__file__).parents[2] / RO_DATA_FILENAME

    Restaurant = apps.get_model('client', 'Restaurant')
    r_jsonfile = Path(__file__).parents[2] / R_DATA_FILENAME

    Order = apps.get_model('client', 'Order')
    o_jsonfile = Path(__file__).parents[2] / O_DATA_FILENAME

    with open(str(ro_jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            try:
                email_address = obj['fields']['email_address']
                password = obj['fields']['password']
                RestaurantOwner(email_address=email_address,
                                password=password).save()
            except KeyError:
                pass

    with open(str(r_jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            try:
                name = obj['fields']['name']
                description = obj['fields']['description']
                location_lon = obj['fields'].get('location_lon', 0)
                location_lat = obj['fields'].get('location_lat', 0)
                operating_hours_start = obj['fields']['operating_hours_start']
                operating_hours_end = obj['fields']['operating_hours_end']
                owner_id = obj['fields']['owner_id']
                image_url = obj['fields']['image_url']
                location = fromstr(
                    f'POINT({location_lon} {location_lat})', srid=4326)
                Restaurant(name=name, description=description, location_lon=location_lon, location_lat=location_lat, operating_hours_start=operating_hours_start,
                           operating_hours_end=operating_hours_end, owner_id=owner_id, image_url=image_url, location=location).save()
            except KeyError:
                pass

    with open(str(o_jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            try:
                total_price = obj['fields']['total_price']
                customer_id = obj['fields']['customer_id']
                Order(total_price=total_price,
                                customer_id=customer_id).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
